# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'audiomanager.ui',
# licensing of 'audiomanager.ui' applies.
#
# Created: Tue Feb  5 16:57:58 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_AudioManager(object):
    def setupUi(self, AudioManager):
        AudioManager.setObjectName("AudioManager")
        AudioManager.resize(984, 682)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(AudioManager)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(AudioManager)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tree_view = QtWidgets.QTreeView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_view.sizePolicy().hasHeightForWidth())
        self.tree_view.setSizePolicy(sizePolicy)
        self.tree_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tree_view.setUniformRowHeights(True)
        self.tree_view.setHeaderHidden(True)
        self.tree_view.setObjectName("tree_view")
        self.tree_view.header().setVisible(False)
        self.details_pane = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_pane.sizePolicy().hasHeightForWidth())
        self.details_pane.setSizePolicy(sizePolicy)
        self.details_pane.setObjectName("details_pane")
        self.gridLayout = QtWidgets.QGridLayout(self.details_pane)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.details_pane)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.details_pane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.details_pane)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.name = QtWidgets.QLabel(self.details_pane)
        self.name.setText("")
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.details_pane)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lbl_duration = QtWidgets.QLabel(self.details_pane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_duration.sizePolicy().hasHeightForWidth())
        self.lbl_duration.setSizePolicy(sizePolicy)
        self.lbl_duration.setObjectName("lbl_duration")
        self.gridLayout.addWidget(self.lbl_duration, 5, 2, 1, 1)
        self.path = QtWidgets.QLabel(self.details_pane)
        self.path.setText("")
        self.path.setObjectName("path")
        self.gridLayout.addWidget(self.path, 1, 1, 1, 1)
        self.time_slider = QtWidgets.QSlider(self.details_pane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_slider.sizePolicy().hasHeightForWidth())
        self.time_slider.setSizePolicy(sizePolicy)
        self.time_slider.setOrientation(QtCore.Qt.Horizontal)
        self.time_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.time_slider.setTickInterval(1)
        self.time_slider.setObjectName("time_slider")
        self.gridLayout.addWidget(self.time_slider, 5, 0, 1, 2)
        self.lbl_spectro = QtWidgets.QLabel(self.details_pane)
        self.lbl_spectro.setMinimumSize(QtCore.QSize(0, 299))
        self.lbl_spectro.setObjectName("lbl_spectro")
        self.gridLayout.addWidget(self.lbl_spectro, 4, 0, 1, 3)
        self.year = QtWidgets.QLabel(self.details_pane)
        self.year.setObjectName("year")
        self.gridLayout.addWidget(self.year, 2, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.splitter)
        self.action_ACI = QtWidgets.QAction(AudioManager)
        self.action_ACI.setObjectName("action_ACI")
        self.action_detect_songs = QtWidgets.QAction(AudioManager)
        self.action_detect_songs.setObjectName("action_detect_songs")

        self.retranslateUi(AudioManager)
        QtCore.QMetaObject.connectSlotsByName(AudioManager)

    def retranslateUi(self, AudioManager):
        AudioManager.setWindowTitle(QtWidgets.QApplication.translate("AudioManager", "Form", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("AudioManager", "compute ACI", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("AudioManager", "Year", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("AudioManager", "Name", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("AudioManager", "Path", None, -1))
        self.lbl_duration.setText(QtWidgets.QApplication.translate("AudioManager", "TextLabel", None, -1))
        self.lbl_spectro.setText(QtWidgets.QApplication.translate("AudioManager", "TextLabel", None, -1))
        self.year.setText(QtWidgets.QApplication.translate("AudioManager", "TextLabel", None, -1))
        self.action_ACI.setText(QtWidgets.QApplication.translate("AudioManager", "Compute ACI", None, -1))
        self.action_detect_songs.setText(QtWidgets.QApplication.translate("AudioManager", "Detect bird songs", None, -1))

