# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'audiomanager.ui',
# licensing of 'audiomanager.ui' applies.
#
# Created: Wed Mar 13 16:21:19 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_AudioManager(object):
    def setupUi(self, AudioManager):
        AudioManager.setObjectName("AudioManager")
        AudioManager.resize(984, 682)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(AudioManager)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(AudioManager)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tree_view = QtWidgets.QTreeView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_view.sizePolicy().hasHeightForWidth())
        self.tree_view.setSizePolicy(sizePolicy)
        self.tree_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tree_view.setUniformRowHeights(True)
        self.tree_view.setHeaderHidden(True)
        self.tree_view.setObjectName("tree_view")
        self.tree_view.header().setVisible(False)
        self.details_pane = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_pane.sizePolicy().hasHeightForWidth())
        self.details_pane.setSizePolicy(sizePolicy)
        self.details_pane.setObjectName("details_pane")
        self.gridLayout = QtWidgets.QGridLayout(self.details_pane)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_export_pdf = QtWidgets.QPushButton(self.details_pane)
        self.btn_export_pdf.setObjectName("btn_export_pdf")
        self.horizontalLayout.addWidget(self.btn_export_pdf)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.details_pane)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 9, 0, 1, 3)
        self.lbl_spectro = QtWidgets.QLabel(self.details_pane)
        self.lbl_spectro.setMinimumSize(QtCore.QSize(0, 299))
        self.lbl_spectro.setObjectName("lbl_spectro")
        self.gridLayout.addWidget(self.lbl_spectro, 6, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.details_pane)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.details_pane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.details_pane)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lbl_year = QtWidgets.QLabel(self.details_pane)
        self.lbl_year.setText("")
        self.lbl_year.setObjectName("lbl_year")
        self.gridLayout.addWidget(self.lbl_year, 3, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.details_pane)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.details_pane)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.lbl_duration = QtWidgets.QLabel(self.details_pane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_duration.sizePolicy().hasHeightForWidth())
        self.lbl_duration.setSizePolicy(sizePolicy)
        self.lbl_duration.setObjectName("lbl_duration")
        self.gridLayout.addWidget(self.lbl_duration, 7, 2, 1, 1)
        self.time_slider = QtWidgets.QSlider(self.details_pane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_slider.sizePolicy().hasHeightForWidth())
        self.time_slider.setSizePolicy(sizePolicy)
        self.time_slider.setOrientation(QtCore.Qt.Horizontal)
        self.time_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.time_slider.setTickInterval(1)
        self.time_slider.setObjectName("time_slider")
        self.gridLayout.addWidget(self.time_slider, 7, 0, 1, 2)
        self.lbl_path = QtWidgets.QLabel(self.details_pane)
        self.lbl_path.setText("")
        self.lbl_path.setObjectName("lbl_path")
        self.gridLayout.addWidget(self.lbl_path, 2, 1, 1, 2)
        self.lbl_name = QtWidgets.QLabel(self.details_pane)
        self.lbl_name.setText("")
        self.lbl_name.setObjectName("lbl_name")
        self.gridLayout.addWidget(self.lbl_name, 1, 1, 1, 2)
        self.lbl_id = QtWidgets.QLabel(self.details_pane)
        self.lbl_id.setText("")
        self.lbl_id.setObjectName("lbl_id")
        self.gridLayout.addWidget(self.lbl_id, 0, 1, 1, 2)
        self.checkbox_draw_events = QtWidgets.QCheckBox(self.details_pane)
        self.checkbox_draw_events.setChecked(True)
        self.checkbox_draw_events.setObjectName("checkbox_draw_events")
        self.gridLayout.addWidget(self.checkbox_draw_events, 5, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.splitter)
        self.action_ACI = QtWidgets.QAction(AudioManager)
        self.action_ACI.setObjectName("action_ACI")
        self.action_detect_songs = QtWidgets.QAction(AudioManager)
        self.action_detect_songs.setObjectName("action_detect_songs")
        self.action_delete = QtWidgets.QAction(AudioManager)
        self.action_delete.setObjectName("action_delete")
        self.action_create_links = QtWidgets.QAction(AudioManager)
        self.action_create_links.setObjectName("action_create_links")

        self.retranslateUi(AudioManager)
        QtCore.QMetaObject.connectSlotsByName(AudioManager)

    def retranslateUi(self, AudioManager):
        AudioManager.setWindowTitle(QtWidgets.QApplication.translate("AudioManager", "Form", None, -1))
        self.btn_export_pdf.setText(QtWidgets.QApplication.translate("AudioManager", "export events", None, -1))
        self.lbl_spectro.setText(QtWidgets.QApplication.translate("AudioManager", "TextLabel", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("AudioManager", "Name", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("AudioManager", "Year", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("AudioManager", "Path", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("AudioManager", "Id", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("AudioManager", "ACI", None, -1))
        self.lbl_duration.setText(QtWidgets.QApplication.translate("AudioManager", "TextLabel", None, -1))
        self.checkbox_draw_events.setText(QtWidgets.QApplication.translate("AudioManager", "Draw events", None, -1))
        self.action_ACI.setText(QtWidgets.QApplication.translate("AudioManager", "Compute ACI", None, -1))
        self.action_detect_songs.setText(QtWidgets.QApplication.translate("AudioManager", "Detect bird songs", None, -1))
        self.action_delete.setText(QtWidgets.QApplication.translate("AudioManager", "Delete", None, -1))
        self.action_create_links.setText(QtWidgets.QApplication.translate("AudioManager", "Create virtual links", None, -1))
        self.action_create_links.setToolTip(QtWidgets.QApplication.translate("AudioManager", "<html><head/><body><p>Create virtual links to files to easily have human readable filenames</p></body></html>", None, -1))

