# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fileimport.ui',
# licensing of 'fileimport.ui' applies.
#
# Created: Sun Aug 12 23:17:05 2018
#      by: pyside2-uic  running on PySide2 5.11.1a1.dev1530708810518
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_FileImport(object):
    def setupUi(self, FileImport):
        FileImport.setObjectName("FileImport")
        FileImport.resize(1096, 621)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(FileImport)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(FileImport)
        self.groupBox.setEnabled(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(1, -1, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        self.overwrite_2 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overwrite_2.sizePolicy().hasHeightForWidth())
        self.overwrite_2.setSizePolicy(sizePolicy)
        self.overwrite_2.setObjectName("overwrite_2")
        self.gridLayout_2.addWidget(self.overwrite_2, 12, 0, 1, 1)
        self.sourceLabel_2 = QtWidgets.QLabel(self.groupBox)
        self.sourceLabel_2.setMaximumSize(QtCore.QSize(169, 16777215))
        self.sourceLabel_2.setMargin(5)
        self.sourceLabel_2.setObjectName("sourceLabel_2")
        self.gridLayout_2.addWidget(self.sourceLabel_2, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.isFolder_2 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isFolder_2.sizePolicy().hasHeightForWidth())
        self.isFolder_2.setSizePolicy(sizePolicy)
        self.isFolder_2.setChecked(True)
        self.isFolder_2.setObjectName("isFolder_2")
        self.buttonGroup = QtWidgets.QButtonGroup(FileImport)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.isFolder_2)
        self.horizontalLayout_4.addWidget(self.isFolder_2)
        self.isFile_2 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isFile_2.sizePolicy().hasHeightForWidth())
        self.isFile_2.setSizePolicy(sizePolicy)
        self.isFile_2.setMinimumSize(QtCore.QSize(0, 0))
        self.isFile_2.setChecked(False)
        self.isFile_2.setObjectName("isFile_2")
        self.buttonGroup.addButton(self.isFile_2)
        self.horizontalLayout_4.addWidget(self.isFile_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setMargin(5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 8, 0, 1, 5)
        self.destPathInput_2 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.destPathInput_2.sizePolicy().hasHeightForWidth())
        self.destPathInput_2.setSizePolicy(sizePolicy)
        self.destPathInput_2.setObjectName("destPathInput_2")
        self.gridLayout_2.addWidget(self.destPathInput_2, 11, 1, 1, 4)
        self.destinationLabel_2 = QtWidgets.QLabel(self.groupBox)
        self.destinationLabel_2.setMargin(5)
        self.destinationLabel_2.setObjectName("destinationLabel_2")
        self.gridLayout_2.addWidget(self.destinationLabel_2, 11, 0, 1, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_2.setEnabled(False)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout_2.addWidget(self.progressBar_2, 15, 0, 1, 3)
        self.convertBtn_2 = QtWidgets.QPushButton(self.groupBox)
        self.convertBtn_2.setObjectName("convertBtn_2")
        self.gridLayout_2.addWidget(self.convertBtn_2, 15, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMargin(5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(FileImport)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton)
        self.horizontalLayout_6.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_3.sizePolicy().hasHeightForWidth())
        self.radioButton_3.setSizePolicy(sizePolicy)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup_2.addButton(self.radioButton_3)
        self.horizontalLayout_6.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_2.sizePolicy().hasHeightForWidth())
        self.radioButton_2.setSizePolicy(sizePolicy)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup_2.addButton(self.radioButton_2)
        self.horizontalLayout_6.addWidget(self.radioButton_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 2, 1, 1, 2)
        self.srcBrowseBtn_2 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcBrowseBtn_2.sizePolicy().hasHeightForWidth())
        self.srcBrowseBtn_2.setSizePolicy(sizePolicy)
        self.srcBrowseBtn_2.setObjectName("srcBrowseBtn_2")
        self.gridLayout_2.addWidget(self.srcBrowseBtn_2, 3, 5, 1, 1)
        self.isRecursive_2 = QtWidgets.QCheckBox(self.groupBox)
        self.isRecursive_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isRecursive_2.sizePolicy().hasHeightForWidth())
        self.isRecursive_2.setSizePolicy(sizePolicy)
        self.isRecursive_2.setChecked(True)
        self.isRecursive_2.setObjectName("isRecursive_2")
        self.gridLayout_2.addWidget(self.isRecursive_2, 1, 3, 1, 1)
        self.destBrowseBtn_2 = QtWidgets.QPushButton(self.groupBox)
        self.destBrowseBtn_2.setObjectName("destBrowseBtn_2")
        self.gridLayout_2.addWidget(self.destBrowseBtn_2, 11, 5, 1, 1)
        self.cancelBtn_2 = QtWidgets.QPushButton(self.groupBox)
        self.cancelBtn_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelBtn_2.sizePolicy().hasHeightForWidth())
        self.cancelBtn_2.setSizePolicy(sizePolicy)
        self.cancelBtn_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cancelBtn_2.setObjectName("cancelBtn_2")
        self.gridLayout_2.addWidget(self.cancelBtn_2, 15, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 12, 2, 1, 3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 12, 1, 1, 1)
        self.logConsole_2 = QtWidgets.QTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logConsole_2.sizePolicy().hasHeightForWidth())
        self.logConsole_2.setSizePolicy(sizePolicy)
        self.logConsole_2.setObjectName("logConsole_2")
        self.gridLayout_2.addWidget(self.logConsole_2, 14, 0, 1, 6)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setEnabled(True)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMargin(5)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 5)
        self.srcPathInput_2 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcPathInput_2.sizePolicy().hasHeightForWidth())
        self.srcPathInput_2.setSizePolicy(sizePolicy)
        self.srcPathInput_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.srcPathInput_2.setObjectName("srcPathInput_2")
        self.gridLayout_2.addWidget(self.srcPathInput_2, 3, 1, 1, 4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_2)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.gridLayout_2.addWidget(self.groupBox_2, 4, 0, 1, 6)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_5.addWidget(self.groupBox)

        self.retranslateUi(FileImport)
        self.comboBox_2.setCurrentIndex(1)
        self.comboBox_3.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(FileImport)

    def retranslateUi(self, FileImport):
        FileImport.setWindowTitle(QtWidgets.QApplication.translate("FileImport", "Import files", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("FileImport", "Import files into database", None, -1))
        self.overwrite_2.setText(QtWidgets.QApplication.translate("FileImport", "Overwrite old files", None, -1))
        self.sourceLabel_2.setText(QtWidgets.QApplication.translate("FileImport", "Source", None, -1))
        self.isFolder_2.setText(QtWidgets.QApplication.translate("FileImport", "Choose a folder", None, -1))
        self.isFile_2.setText(QtWidgets.QApplication.translate("FileImport", "Choose files", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("FileImport", "<b>Please select the destination folder</b>", None, -1))
        self.destinationLabel_2.setText(QtWidgets.QApplication.translate("FileImport", "Destination", None, -1))
        self.convertBtn_2.setText(QtWidgets.QApplication.translate("FileImport", "Convert", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("FileImport", "File type", None, -1))
        self.radioButton.setText(QtWidgets.QApplication.translate("FileImport", "Auto-detect", None, -1))
        self.radioButton_3.setText(QtWidgets.QApplication.translate("FileImport", "SongMeter", None, -1))
        self.radioButton_2.setText(QtWidgets.QApplication.translate("FileImport", "Audiomoth", None, -1))
        self.srcBrowseBtn_2.setText(QtWidgets.QApplication.translate("FileImport", "Browse", None, -1))
        self.isRecursive_2.setText(QtWidgets.QApplication.translate("FileImport", "include subfolders", None, -1))
        self.destBrowseBtn_2.setText(QtWidgets.QApplication.translate("FileImport", "Browse", None, -1))
        self.cancelBtn_2.setText(QtWidgets.QApplication.translate("FileImport", "Cancel", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("FileImport", "<html><head/><body><p><span style=\" font-weight:600;\">Note:</span> WAC files will automatically be decompressed for future analyses</p></body></html>", None, -1))
        self.checkBox_2.setText(QtWidgets.QApplication.translate("FileImport", "Convert files to FLAC", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("FileImport", "<b>Please select the files to import</b>", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("FileImport", "Automatically detect information from folder hierarchy and match folders to the following information:  f", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("FileImport", "Root folder", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("FileImport", "Site", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("FileImport", "Year", None, -1))
        self.comboBox.setItemText(2, QtWidgets.QApplication.translate("FileImport", "Plot", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("FileImport", "Subfolder 1", None, -1))
        self.comboBox_2.setItemText(0, QtWidgets.QApplication.translate("FileImport", "Site", None, -1))
        self.comboBox_2.setItemText(1, QtWidgets.QApplication.translate("FileImport", "Year", None, -1))
        self.comboBox_2.setItemText(2, QtWidgets.QApplication.translate("FileImport", "Plot", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("FileImport", "Subfolder 2", None, -1))
        self.comboBox_3.setItemText(0, QtWidgets.QApplication.translate("FileImport", "Site", None, -1))
        self.comboBox_3.setItemText(1, QtWidgets.QApplication.translate("FileImport", "Year", None, -1))
        self.comboBox_3.setItemText(2, QtWidgets.QApplication.translate("FileImport", "Plot", None, -1))

