# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fileimport.ui',
# licensing of 'fileimport.ui' applies.
#
# Created: Sun Aug 12 21:48:02 2018
#      by: pyside2-uic  running on PySide2 5.11.1a1.dev1530708810518
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_FileImport(object):
    def setupUi(self, FileImport):
        FileImport.setObjectName("FileImport")
        FileImport.resize(1096, 621)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(FileImport)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(FileImport)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(1, -1, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.isFolder_2 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isFolder_2.sizePolicy().hasHeightForWidth())
        self.isFolder_2.setSizePolicy(sizePolicy)
        self.isFolder_2.setChecked(True)
        self.isFolder_2.setObjectName("isFolder_2")
        self.horizontalLayout_4.addWidget(self.isFolder_2)
        self.isFile_2 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isFile_2.sizePolicy().hasHeightForWidth())
        self.isFile_2.setSizePolicy(sizePolicy)
        self.isFile_2.setMinimumSize(QtCore.QSize(0, 0))
        self.isFile_2.setChecked(False)
        self.isFile_2.setObjectName("isFile_2")
        self.horizontalLayout_4.addWidget(self.isFile_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 0, 1, 2)
        self.logConsole_2 = QtWidgets.QTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logConsole_2.sizePolicy().hasHeightForWidth())
        self.logConsole_2.setSizePolicy(sizePolicy)
        self.logConsole_2.setObjectName("logConsole_2")
        self.gridLayout_2.addWidget(self.logConsole_2, 10, 0, 1, 5)
        self.convertBtn_2 = QtWidgets.QPushButton(self.groupBox)
        self.convertBtn_2.setObjectName("convertBtn_2")
        self.gridLayout_2.addWidget(self.convertBtn_2, 11, 4, 1, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_2.setEnabled(False)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout_2.addWidget(self.progressBar_2, 11, 0, 1, 2)
        self.destinationLabel_2 = QtWidgets.QLabel(self.groupBox)
        self.destinationLabel_2.setMargin(5)
        self.destinationLabel_2.setObjectName("destinationLabel_2")
        self.gridLayout_2.addWidget(self.destinationLabel_2, 7, 0, 1, 1)
        self.destBrowseBtn_2 = QtWidgets.QPushButton(self.groupBox)
        self.destBrowseBtn_2.setObjectName("destBrowseBtn_2")
        self.gridLayout_2.addWidget(self.destBrowseBtn_2, 7, 4, 1, 1)
        self.srcBrowseBtn_2 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcBrowseBtn_2.sizePolicy().hasHeightForWidth())
        self.srcBrowseBtn_2.setSizePolicy(sizePolicy)
        self.srcBrowseBtn_2.setObjectName("srcBrowseBtn_2")
        self.gridLayout_2.addWidget(self.srcBrowseBtn_2, 2, 4, 1, 1)
        self.overwrite_2 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overwrite_2.sizePolicy().hasHeightForWidth())
        self.overwrite_2.setSizePolicy(sizePolicy)
        self.overwrite_2.setObjectName("overwrite_2")
        self.gridLayout_2.addWidget(self.overwrite_2, 8, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 8, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMargin(5)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 5)
        self.cancelBtn_2 = QtWidgets.QPushButton(self.groupBox)
        self.cancelBtn_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelBtn_2.sizePolicy().hasHeightForWidth())
        self.cancelBtn_2.setSizePolicy(sizePolicy)
        self.cancelBtn_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cancelBtn_2.setObjectName("cancelBtn_2")
        self.gridLayout_2.addWidget(self.cancelBtn_2, 11, 3, 1, 1)
        self.destPathInput_2 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.destPathInput_2.sizePolicy().hasHeightForWidth())
        self.destPathInput_2.setSizePolicy(sizePolicy)
        self.destPathInput_2.setObjectName("destPathInput_2")
        self.gridLayout_2.addWidget(self.destPathInput_2, 7, 1, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.srcPathInput_2 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcPathInput_2.sizePolicy().hasHeightForWidth())
        self.srcPathInput_2.setSizePolicy(sizePolicy)
        self.srcPathInput_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.srcPathInput_2.setObjectName("srcPathInput_2")
        self.gridLayout_2.addWidget(self.srcPathInput_2, 2, 1, 1, 3)
        self.isRecursive_2 = QtWidgets.QCheckBox(self.groupBox)
        self.isRecursive_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isRecursive_2.sizePolicy().hasHeightForWidth())
        self.isRecursive_2.setSizePolicy(sizePolicy)
        self.isRecursive_2.setChecked(True)
        self.isRecursive_2.setObjectName("isRecursive_2")
        self.gridLayout_2.addWidget(self.isRecursive_2, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setMargin(5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 5)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMargin(5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 9, 0, 1, 1)
        self.sourceLabel_2 = QtWidgets.QLabel(self.groupBox)
        self.sourceLabel_2.setMaximumSize(QtCore.QSize(169, 16777215))
        self.sourceLabel_2.setMargin(5)
        self.sourceLabel_2.setObjectName("sourceLabel_2")
        self.gridLayout_2.addWidget(self.sourceLabel_2, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_6.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_3.sizePolicy().hasHeightForWidth())
        self.radioButton_3.setSizePolicy(sizePolicy)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_6.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_2.sizePolicy().hasHeightForWidth())
        self.radioButton_2.setSizePolicy(sizePolicy)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_6.addWidget(self.radioButton_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 9, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 9, 2, 1, 3)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_5.addWidget(self.groupBox)

        self.retranslateUi(FileImport)
        QtCore.QMetaObject.connectSlotsByName(FileImport)

    def retranslateUi(self, FileImport):
        FileImport.setWindowTitle(QtWidgets.QApplication.translate("FileImport", "Form", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("FileImport", "Import files into database", None, -1))
        self.isFolder_2.setText(QtWidgets.QApplication.translate("FileImport", "Choose a folder", None, -1))
        self.isFile_2.setText(QtWidgets.QApplication.translate("FileImport", "Choose files", None, -1))
        self.convertBtn_2.setText(QtWidgets.QApplication.translate("FileImport", "Convert", None, -1))
        self.destinationLabel_2.setText(QtWidgets.QApplication.translate("FileImport", "Destination", None, -1))
        self.destBrowseBtn_2.setText(QtWidgets.QApplication.translate("FileImport", "Browse", None, -1))
        self.srcBrowseBtn_2.setText(QtWidgets.QApplication.translate("FileImport", "Browse", None, -1))
        self.overwrite_2.setText(QtWidgets.QApplication.translate("FileImport", "Overwrite old files", None, -1))
        self.checkBox_2.setText(QtWidgets.QApplication.translate("FileImport", "Convert files to FLAC", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("FileImport", "<b>Please select the files to import</b>", None, -1))
        self.cancelBtn_2.setText(QtWidgets.QApplication.translate("FileImport", "Cancel", None, -1))
        self.isRecursive_2.setText(QtWidgets.QApplication.translate("FileImport", "include subfolders", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("FileImport", "<b>Please select the destination folder</b>", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("FileImport", "File type", None, -1))
        self.sourceLabel_2.setText(QtWidgets.QApplication.translate("FileImport", "Source", None, -1))
        self.radioButton.setText(QtWidgets.QApplication.translate("FileImport", "Autodetect", None, -1))
        self.radioButton_3.setText(QtWidgets.QApplication.translate("FileImport", "SongMeter", None, -1))
        self.radioButton_2.setText(QtWidgets.QApplication.translate("FileImport", "Audiomoth", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("FileImport", "<b>Note:</b> WAC files will automatically be converted", None, -1))

