# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectrogramsettings.ui',
# licensing of 'spectrogramsettings.ui' applies.
#
# Created: Sat Oct 26 12:49:18 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SpectrogramSettings(object):
    def setupUi(self, SpectrogramSettings):
        SpectrogramSettings.setObjectName("SpectrogramSettings")
        SpectrogramSettings.resize(636, 566)
        self.gridLayout = QtWidgets.QGridLayout(SpectrogramSettings)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(SpectrogramSettings)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(SpectrogramSettings)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.checkbox_normalize = QtWidgets.QCheckBox(SpectrogramSettings)
        self.checkbox_normalize.setText("")
        self.checkbox_normalize.setObjectName("checkbox_normalize")
        self.gridLayout.addWidget(self.checkbox_normalize, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(SpectrogramSettings)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.combobox_fft = QtWidgets.QComboBox(SpectrogramSettings)
        self.combobox_fft.setObjectName("combobox_fft")
        self.combobox_fft.addItem("")
        self.combobox_fft.addItem("")
        self.combobox_fft.addItem("")
        self.combobox_fft.addItem("")
        self.combobox_fft.addItem("")
        self.gridLayout.addWidget(self.combobox_fft, 2, 1, 1, 1)
        self.combobox_spec_window = QtWidgets.QComboBox(SpectrogramSettings)
        self.combobox_spec_window.setObjectName("combobox_spec_window")
        self.combobox_spec_window.addItem("")
        self.gridLayout.addWidget(self.combobox_spec_window, 3, 1, 1, 1)
        self.combobox_scale = QtWidgets.QComboBox(SpectrogramSettings)
        self.combobox_scale.setObjectName("combobox_scale")
        self.combobox_scale.addItem("")
        self.combobox_scale.addItem("")
        self.gridLayout.addWidget(self.combobox_scale, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(SpectrogramSettings)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(SpectrogramSettings)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(SpectrogramSettings)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.checkbox_to_db = QtWidgets.QCheckBox(SpectrogramSettings)
        self.checkbox_to_db.setText("")
        self.checkbox_to_db.setChecked(True)
        self.checkbox_to_db.setObjectName("checkbox_to_db")
        self.gridLayout.addWidget(self.checkbox_to_db, 5, 1, 1, 1)
        self.remove_noise = QtWidgets.QGroupBox(SpectrogramSettings)
        self.remove_noise.setCheckable(True)
        self.remove_noise.setObjectName("remove_noise")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.remove_noise)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineedit_noise_N = QtWidgets.QLineEdit(self.remove_noise)
        self.lineedit_noise_N.setObjectName("lineedit_noise_N")
        self.gridLayout_2.addWidget(self.lineedit_noise_N, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.remove_noise)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.remove_noise)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineedit_noise_hist_rel_size = QtWidgets.QLineEdit(self.remove_noise)
        self.lineedit_noise_hist_rel_size.setObjectName("lineedit_noise_hist_rel_size")
        self.gridLayout_2.addWidget(self.lineedit_noise_hist_rel_size, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.remove_noise)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.lineedit_noise_window = QtWidgets.QLineEdit(self.remove_noise)
        self.lineedit_noise_window.setObjectName("lineedit_noise_window")
        self.gridLayout_2.addWidget(self.lineedit_noise_window, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.remove_noise, 7, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(SpectrogramSettings)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.checkbox_pcen = QtWidgets.QCheckBox(SpectrogramSettings)
        self.checkbox_pcen.setText("")
        self.checkbox_pcen.setObjectName("checkbox_pcen")
        self.gridLayout.addWidget(self.checkbox_pcen, 4, 1, 1, 1)

        self.retranslateUi(SpectrogramSettings)
        self.combobox_fft.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(SpectrogramSettings)

    def retranslateUi(self, SpectrogramSettings):
        SpectrogramSettings.setWindowTitle(QtWidgets.QApplication.translate("SpectrogramSettings", "Form", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("SpectrogramSettings", "FFT", None, -1))
        self.label_4.setToolTip(QtWidgets.QApplication.translate("SpectrogramSettings", "<html><head/><body><p>test tooltip</p><p><br/></p></body></html>", None, -1))
        self.label_4.setWhatsThis(QtWidgets.QApplication.translate("SpectrogramSettings", "<html><head/><body><p>Test whatsthis</p><p><br/></p></body></html>", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("SpectrogramSettings", "Normalize", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("SpectrogramSettings", "Window", None, -1))
        self.combobox_fft.setItemText(0, QtWidgets.QApplication.translate("SpectrogramSettings", "128", None, -1))
        self.combobox_fft.setItemText(1, QtWidgets.QApplication.translate("SpectrogramSettings", "256", None, -1))
        self.combobox_fft.setItemText(2, QtWidgets.QApplication.translate("SpectrogramSettings", "512", None, -1))
        self.combobox_fft.setItemText(3, QtWidgets.QApplication.translate("SpectrogramSettings", "1024", None, -1))
        self.combobox_fft.setItemText(4, QtWidgets.QApplication.translate("SpectrogramSettings", "2048", None, -1))
        self.combobox_spec_window.setItemText(0, QtWidgets.QApplication.translate("SpectrogramSettings", "Hanning", None, -1))
        self.combobox_scale.setItemText(0, QtWidgets.QApplication.translate("SpectrogramSettings", "Linear", None, -1))
        self.combobox_scale.setItemText(1, QtWidgets.QApplication.translate("SpectrogramSettings", "Mel", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("SpectrogramSettings", "Scale", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("SpectrogramSettings", "Spectrogram Settings", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("SpectrogramSettings", "Convert to decibels", None, -1))
        self.remove_noise.setTitle(QtWidgets.QApplication.translate("SpectrogramSettings", "Remove noise", None, -1))
        self.lineedit_noise_N.setText(QtWidgets.QApplication.translate("SpectrogramSettings", "0.1", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("SpectrogramSettings", "N", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("SpectrogramSettings", "hist_rel_size", None, -1))
        self.lineedit_noise_hist_rel_size.setText(QtWidgets.QApplication.translate("SpectrogramSettings", "2", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("SpectrogramSettings", "window_smoothing", None, -1))
        self.lineedit_noise_window.setText(QtWidgets.QApplication.translate("SpectrogramSettings", "5", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("SpectrogramSettings", "Use PCEN", None, -1))

